version: '3.8'

services:
  house-prices:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./logs:/app/logs
    environment:
      - DATA_PATH=/app/data
      - MODELS_PATH=/app/saved_models
      - LOGS_PATH=/app/logs 